// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHZnmsZGClUbjYRiWMPt87dxAzp5bbiMM',
    appId: '1:670248556682:web:5833fabc298014bf85b573',
    messagingSenderId: '670248556682',
    projectId: 'hackboura',
    authDomain: 'hackboura.firebaseapp.com',
    storageBucket: 'hackboura.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDol5LMnEBnYuDTTxHE7mWoHQkSPcnWNsw',
    appId: '1:670248556682:android:b64c45b64e39576585b573',
    messagingSenderId: '670248556682',
    projectId: 'hackboura',
    storageBucket: 'hackboura.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAop6Fi7_n9s9RigGQcFeMrO08msaIKs2M',
    appId: '1:670248556682:ios:c700747049fbda7f85b573',
    messagingSenderId: '670248556682',
    projectId: 'hackboura',
    storageBucket: 'hackboura.appspot.com',
    iosClientId: '670248556682-1e1aeo35qop1ifqjnu7941b6hnr4g73c.apps.googleusercontent.com',
    iosBundleId: 'com.hackbourak.flutterfest',
  );
}
